config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
  resources :contacts, only: [:new, :create]
  get 'resume/index'
  get 'welcome/index'
  root 'welcome#index'

  get '*path!' => redirect('/')
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,     :validate => true
	attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,  :validate => true
	attribute :nickname, :captcha  => true

	def headers 
	{
		:subject => "Contact Form",
		:to => "Milhound@gmail.com",
		:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, :use => :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
	@contact = Contact.new
end

def create
	@contact = Contact.new(params[:contact])
	@contact.request = request
	if @contact.deliver
		flash.now[:error] = nil
	else
		flash.now[:error] = "Cannot send message"
		render :new
	end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_posts, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!, except: [:index, :show]
	
	def index
		@post = Post.order('created_at desc').all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post, notice: "Saved"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Updated"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to :posts
	end

	private

	def find_posts
		@post = Post.friendly.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
	def index
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@post = Post.order('created_at desc').first('3')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div class="center">
	<h1>Thank You!</h1>
	<p> I will get back to  you as soon as possible! </p>
</div>

app/views/contacts/new.html.erb
<h1> Contact Form </h1>
<div class="narrow-wrapper">
	<%= form_for @contact do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :message %>
	<%= f.text_area :message %>
	<%= f.text_field :nickname, :class => 'hidden' %>
	<%= f.submit %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test Website</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href="https://file.myfontastic.com/n6vo44Re5QaWo8oCKShBs7/icons.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<header class="clearfix">
	<%= link_to "Daniel Milholland", welcome_index_path , id: 'logo' %>
	<nav id="nav">
		<ul>
			<li class="mini-screen">
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "Blog", posts_path %>
			</li>
			<li>
				<%= link_to "Contact", new_contact_path %>
			</li>
			<li>
				<%= link_to "Resume", resume_index_path %>
			</li>
			<% if admin_signed_in? %>
			<li>
				<%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
			</li>
			<% end %>
		</ul>
	</nav>
	</header>	
	<div class="wrapper clearfix">
	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
<h4><%= f.label :title %><h4>
<%= f.text_field :title %>
<br>
<h4><%= f.label :content %></h4>
<%= f.text_area :content %><br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="post">
	<h1> Edit Page </h1>
	<%= render 'form'%>
</div>

app/views/posts/index.html.erb
<div id="post">

	<h1 class='title'>blog</h1>
	<% if admin_signed_in? %>
		<div class="special-buttons">
			<%= link_to "New", new_post_path%>
		</div>
	<% end %>
	<% @post.each do |post| %>
		<h3><%= post.title %></h3>
		<hr class="decoration">
		<div class="content">
			<p><%= markdown truncate( post.content, :length => 50) %></p>
			<br>
			<% if admin_signed_in? %>
				<%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}  %>
				<%= link_to "Edit", edit_post_path(post)%>
			<% end %>
			<%= link_to "View", post_path(post) %>
		</div>
	<% end %>
	<br>
</div>

app/views/posts/new.html.erb
<div id="post">
	<h1>New Post</h1>

	<%= render :partial => 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post">
	<div id="blog" class="wrapper">
		<h1 id="blog-title"><%= @post.title %></h1>
		<div id="socialbtns">
		SHARE:
			<span onclick="javascript:window.open('https://twitter.com/home?status=<%= @post.title %>%20-%20by%20%40Milhound%20%20<%= url_for(:only_path => false) %>', '_blank', 'toolbar=no,width=500, height=300, left=450, top=200');" class="socicon-twitter"></span>
			<span onclick="javascript:window.open('https://www.facebook.com/sharer.php?u=<%= url_for(:only_path => false) %>', '_blank', 'toolbar=no, width=500, height=300, left=450, top=200');" class="socicon-facebook"></span>
			<span onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for(:only_path => false) %>', '_blank', 'toolbar=no,width=500, height=300, left=450, top=200');" class="socicon-googleplus"></span>
		</div>
		<p class="clearfix"><%= markdown @post.content %></p>
		<br>
		<%= link_to "All Blogs", posts_path %>
		<% if admin_signed_in? %>
			<%= link_to "Edit", edit_post_path%>
			<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
		<% end %>
		<br>
		<br>
		<div id="disqus_thread"></div>
		<script>
			/*
			var disqus_config = function () {
			this.page.url = <%=request.host%>;
			this.page.identifier = <%=request.fullpath;
			};
			*/
			(function() { // DON'T EDIT BELOW THIS LINE
			var d = document, s = d.createElement('script');

			s.src = '//milhound.disqus.com/embed.js';

			s.setAttribute('data-timestamp', +new Date());
			(d.head || d.body).appendChild(s);
			})();
		</script>
		<noscript>
		Please enable JavaScript to view the 	<a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

	</div>
</div>

app/views/resume/index.html.erb
<div id="resume">
	<h1 class="title">RESUME</h1>
	<h3 class="title">Daniel Milholland</h3>
	<h3>Goal</h3>
	<p>
	My career goal is to aquire a job in the Software Development or Information Security field. 
	With a passion in computers that started at a young age, I've always strived to learn everything  
	about computers and how they work. During my service as a Correctional 
	Officer for the Texas Department of Criminal Justice my interest in Computer Security grew even further. 
	</p>
	<h3>Education</h3>
	<p>
	University of Texas-San Antonio <span>December 2012-Present</span><br>
	Bachelor of Science in Computer Science<br>
	<br>
	Oak Ridge High School<span>Graduated May 2011</span><br>
	Conroe, TX<br>
	</p>
	<h3>Certifications</h3>
	<p>
	*	10-Hour OSHA Training Course in General Industry Safety and Health<br>
	*	STA Clearance from TSA (Security Threat Assessment for Homeland Security)<br>
	*	Currently Certified Forklift Driver<br>
	*	Hazmat Certified<br>
	</p>    
	<h3>Skills</h3>
	<p>
	<b>DEVELOPMENT SKILLS</b><br> 
	*   Python - Intermediate<br>
	*   Java SE - Intermediate<br>
	*   C# - Intermediate<br>
	*   HTML5/CSS - Intermediate<br>
	*	Networking - Intermediate<br>
	<br>
	<b>MANAGEMENT SKILLS</b><br>
	*	Strong Supervisory Skills<br>
	*	Plan Development<br>
	*   Time Management</br>
	*	Self-Motivated<br>
	<br>
	<b>SECURITY SKILLS</b><br>
	(TDCJ employed from 2012 – 2013)<br>
	*	5+ Years Monitoring Warehouses<br>
	*	Inventorying equipment<br>
	</p>
	<h3>Employment History</h3>
	<p>
	<b>GAIL WINDS LOGISTICS</b> – Houston, TX<span>July 1, 2013 – Present</span><br>
	Freight Forwarder/Computer Specialist/Warehouse Manager<br>
	<br>
	<b>HSS SECURITY</b> – San Antonio, TX<span>March 22, 2013 – July 1, 2013</span><br>
	Security Officer<br>
	<br>
	<b>TEXAS DEPARTMENT OF CRIMINAL JUSTICE</b> – Huntsville, TX<span>January 4, 2012 – March 20, 2013</span><br>
	Correctional Officer - III<br>
	<br>
	<b>TARGET CORPORATION</b> – Spring, TX<span>June 2011 – November 2011</span><br>
	Flow Team Member/Back stock<br>
	<br>
	<b>GAIL WINDS LOGISTICS</b> – Houston, TX<span>June 2006 – November 2011</span><br>
	Warehouse Operator<br>
	</p>
	<h3>Organizations</h3>
	<p>
	<b>CORRECTIONAL PEACE OFFICER FOUNDATION (CPOF)</b> – Huntsville, TX<br>
	    Member – January 4th, 2012 – January 1st, 2014<br>
	<br>
	<b>AMERICIAN FEDERATION OF STATE COUNTY AND MUNICIPAL EMPLOYEES</b> – Huntsville, TX<br>
	    Member – January 4th, 2012 – January 1st, 2014<br>
	<br>
	<b>AMERICAN CORRECTIONAL ASSOCIATION (ACA)</b> – Huntsville, TX<br>
	    Member – January 4th, 2012 – January 1st, 2014<br>
	<br>
	<b>ORDER OF THE ARROW</b> – Houston, TX<br>
	    Member – Brother Hood 2008 – Present<br>
	<br>
	<b>BOY SCOUTS OF AMERICA</b> – Spring, TX<br>
	    Tender Foot – Life Scout 2002 – 2012<br>
	</p>
	<h3>Honors</h3>
	<p>
	Life Scout<br>
	Brotherhood – Order of the Arrow<br>
	</p>
</div>
	   

app/views/welcome/index.html.erb
<div id="main-content">
	<h1 id="welcome">Welcome to my Website</h1>
	<div class="col-1">
		<%= image_tag('Daniel.jpg', class: 'profile-pic')%>
		<div id="contact">
			<h3>Contact</h3>
            <ul id="contact-list">
                <li><a href="mailto:Daniel@gailwindslog.com?Subject=Milhound.com%20-%20(Contact)" target="_top">Email</a></li>
                <li><a href="https://twitter.com/Milhound">Twitter</a></li>
                <li><a href="https://www.linkedin.com/in/milholland">Linkedin</a></li>
                <li><a href="skype:milhound?call" alt="Milhound">Skype</a></li>
                <li><a href="https://facebook.com/Milhound">Facebook</a></li>
                <li><a href="https://youtube.com/c/Milhoundz">Youtube</a></li>
                <li><a href="https://github.com/Milhound">GitHub</a>
                </li>
            </ul>
        </div>
	</div>
	<div class="col-2">
		<p>
		Mlkshk blue bottle humblebrag 3 wolf moon mixtape. Twee try-hard forage austin, blue bottle cold-pressed shoreditch you probably haven't heard of them. Small batch narwhal bitters keytar yr waistcoat, tacos shabby chic venmo whatever heirloom meditation kale chips banjo. Meh craft beer disrupt +1, chartreuse flexitarian chillwave. Listicle plaid mlkshk, health goth keffiyeh vice celiac crucifix wolf cold-pressed. Chillwave seitan YOLO pug paleo. Fingerstache art party authentic truffaut offal cronut put a bird on it lo-fi, waistcoat four dollar toast artisan yr twee.
		</p>
		<h3>Recent Blog Posts</h3>
		<div class="blog-posts">
			<% @post.each do |post| %>
				<h5><%= post.title %></h5>
				<p>
					<%= markdown truncate(post.content, :length => 50) %>
					<%= link_to "Go To..", post_path(post) %>
				</p>
			<% end %>
		</div>
		<br>
		<br>
	</div>
</div>